config:
  project_repos:
    o3api:
      repo: 'https://git.scc.kit.edu/synergy.o3as/o3api.git'
      branch: test
      dockerhub: o3as/o3api
      dockertag: latest

sqa_criteria:
  qc_style:
    repos:
      o3api:
        container: o3api-testing
        tox:
          tox_file: /o3api-testing/tox.ini
          testenv:
            - pep8
  qc_coverage:
    repos:
      o3api:
        container: o3api-testing
        tox:
          tox_file: /o3api-testing/tox.ini
          testenv: 
            - cover
            - cobertura
  qc_security:
    repos:
      o3api:
        container: o3api-testing
        tox:
          tox_file: /o3api-testing/tox.ini
          testenv:
            - bandit

#environment:
#  LANG: C.UTF-8

timeout: 900
