version: "3.6"

services:
  o3api-testing:
    image: "indigodatacloud/ci-images:python3.6"
    hostname: "o3api-testing"
    volumes:
     - type: bind
       source: ./o3api
       target: /o3api-testing
