version: '3.7'

services:
  o3api:
    image: o3as/o3api
    build:
      context: .
      args:
        branch: master
    volumes:
        - $HOME/datasets/o3as-data:/srv/o3api/data:ro
    ports:
        - 5005:5005
    entrypoint:
        - /srv/o3api/start.sh

# To run with an existing Docker image:
# `$ docker-compose up -d
# To build your own image and immediately run:
# `$ docker-compose up -d --build`
